[package]
name = "typesense"
version = "0.1.0"
authors = ["Typesense  <contact@typesense.org>"]
edition = "2018"

[features]
default = ["tokio_rt", "wasm"]
tokio_rt = ["hyper/runtime", "hyper/tcp", "hyper-tls", "tokio"]
wasm = ["js-sys", "wasm-bindgen", "wasm-bindgen-futures", "web-sys"]

[dependencies]
async-trait = "0.1.50"
http = "0.2.4"
hyper = { version = "0.14.7", features = ["http1", "http2", "client"], optional = true }
hyper-tls = { version = "0.5.0", optional = true }
js-sys = { version = "0.3.50", optional = true }
thiserror = "1.0.24"
tokio = { version = "1.5.0", optional = true }
wasm-bindgen = { version = "0.2.73", optional = true }
wasm-bindgen-futures = { version = "0.4.23", optional = true }
web-sys = { version = "0.3.50", features = ["Headers", "Response", "Request", "RequestInit", "Window", "WorkerGlobalScope"], optional = true }

[dev-dependencies]
httpmock = "0.5.8"
tokio = { version = "1.5.0", features = ["macros", "rt", "rt-multi-thread"] }
